### PR TITLE
Phd theses

### PR DESCRIPTION
**Pull request by birocoles**
Since 2011, all defended theses have been sent to a new platform called [Sucupira](https://sucupira.capes.gov.br/sucupira/public/index.jsf). The Sucupira contains all information about the defended theses and is more stable than the ON page (see [my thesis](https://sucupira.capes.gov.br/sucupira/public/consultas/coleta/trabalhoConclusao/viewTrabalhoConclusao.jsf?popup=true&id_trabalho=314927#), for example).

I think we should include a link to this platform in the page of all thesis. What do you think about it @leouieda?

Besides, the pdf files sent to Sucupira have the page with the signature of the members forming the thesis committee. I am replacing the pdf files without the signed page.

### CODE REVIEW

**Comment by birocoles** [comment]
@leouieda,

What do you think about creating a link for "related scientific production" (or something like this) in each paper and thesis page? In our group, several papers and theses are related to each other. Some paper, however, were developed as an independent work. I have included some text about it in my thesis page, as well as in the thesis page of Dio and Figura.

**Comment by leouieda** [comment]
@birocoles OK, I didn't know about the PDFs in Sucupira. It would be good to link to those pages. I'll add a metadata entry for the Sucupira link and it should appear in the side bar. I'll push it to this PR.

Also, it would be great to have the papers linked to the thesis and vice-versa. Maybe by adding a metdata entry:

`related: /papers/paper-polynomial-eqlayer-2013, /papers/paper-radial3d-gradients-2013`

That could be accepted in papers and thesis to indicated related research. Then the templates would add a "Related research" to the bottom of the Info side bar. This could also be used to link papers that are continuation of the same project, for example your bolachinha papers.

**Comment by leouieda** [comment]
I'm going to implement these things in this branch, OK? I have some free time now.

**Comment by leouieda** [comment]
@birocoles done. Can you build on your side and take a look if this is what you had in mind?

**Comment by birocoles** [comment]
@leouieda, I will do it as soon as possible. Now I am enjoying a nice hangover 🍻

**Comment by leouieda** [comment]
🥂

**Comment by birocoles** [comment]
@leouieda, this is exactly what I had in mind. I think we are ready to merge.

**Comment by leouieda** [comment]
Done 👍

**Pull request merged**
